version: "3"
services:
  web:
    container_name: Front
    image: node:18.18-alpine3.17
    restart: unless-stopped
    working_dir: /usr/src/app
    # command: sh -c "yarn install && yarn run dev"
    command: sh -c "yarn run dev"
    env_file: .env
    environment:
      NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED}
      PORT: ${NEXT_PORT}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./web:/usr/src/app
    ports:
      - ${NEXT_PORT}:${NEXT_PORT}
    networks: 
      - unipopular

  postgres:
    container_name: DB
    image: postgres:16-alpine3.18
    restart: unless-stopped
    command: -p ${DB_PORT}
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./datadb/postgres:/var/lib/postgresql/data
      - ./datadb/dump:/dump
    ports: 
      - ${DB_PORT}:${DB_PORT}
    networks: 
      - unipopular

networks: 
  unipopular:
    name: UniPopular
    driver: bridge
